### ISSUE TITLE
Any way to create add and delete namespaces 

### ISSUE THREAD

**Issue by florianrommel** [ManageIQ/kubeclient#496]
Badass work so far.. but i really need a way to create and delete namespaces.. is there any method? create_namespace etc requires namespace already

**Comment by cben** [comment]
Do these work?
```
client.create_namespace(Kubeclient::Resource.new(metadata: { name: 'foo-bar' }))

client.delete_namespace('name')
# or if you need options:
client.delete_namespace('name', nil, delete_options: {...})
```

**Comment by cben** [comment]
See also summary of namespaced vs global resources at https://github.com/abonas/kubeclient#supported-actions--examples
