### ISSUE TITLE
adding more get_ functions

### ISSUE THREAD

**Issue by florianrommel** [ManageIQ/kubeclient#519]
Hi, can you document how to add more get_, create_ or update_ functions such as get_certificates , get_ingress ,get_namespaces with a filter for example etc.. 
the Gem is very cool to use and if i could i would add these myself but unfortunately i cannot.

**Comment by cben** [comment]
Note that you need to create a separate `Client` object for each API group.  It'll automatically get methods for resource types in that group.  See README for details on `Client` initialization.
For example let's see which group Ingress objects belong to:
```yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
```
this means you need something like:
```
# note how you have to split the apiVersion (annoying, but that's currently how it works):
networking_client = Kubeclient::Client.new('http://localhost:8080/apis/networking.k8s.io', 'v1')
networking_client.get_ingresses(...)
```

Does that help?

**Comment by florianrommel** [comment]
ohh... thats neat.. sorry was offline for a while.. will try that.. this will shrink our code down a lot..
