### ISSUE TITLE
Creating Token Reviews?

### ISSUE THREAD

**Issue by johnnyb** [ManageIQ/kubeclient#562]
How do you create token reviews?  client.create_tokenreview did not work.  Not sure If this is an issue with me, the software, or the documentation.

**Comment by cben** [comment]
What is the API group of TokenReview resources?  Did you create a Client object with this group?  Currently you need separate Client object for each group, search README for "group" for examples...

**Comment by johnnyb** [comment]
Ah, I see.  Thanks.
