### ISSUE TITLE
`watch_entities` does not watch custom resources.

### ISSUE THREAD

**Issue by ypwu1** [ManageIQ/kubeclient#565]
`watch_entities` or dynamic watch method works only on Kubernetes default resources such as `pods`, `events`, `services` etc.  However, when trying use custom resources will received following error:
```
{
  "kind": "Status",
  "apiVersion": "v1",
  "metadata": {

  },
  "status": "Failure",
  "message": "the server could not find the requested resource",
  "reason": "NotFound",
  "details": {

  },
  "code": 404
}
```

**Comment by cben** [comment]
Are you using the correct API group?
- What's the `kind` and `apiVersion` of the desired resource?  (either check an example of such resource, or look at the CRD definition)
- With what parameters did you initialize `Kubeclient::Client`?
 
A `Client` good for pods, services etc. is a basic `.../api', 'v1'` client but your CRDs are probably in another API group and need a distinct Client object.

**Comment by cben** [comment]
closing inactive "question" issues to keep list clean, but feel free to reply / reopen.
