### ISSUE TITLE
Getting invalid uri error when providing a url with IPv6 value

### ISSUE THREAD

**Issue by harshit-splunk** [ManageIQ/kubeclient#578]
**How to reproduce**
Create a client as following:
```ruby
client = Kubeclient::Client.new(
    "https://aaaa:aaaa:aaaa::1:443/api",
    "v1",
    {}
)
```
It throws `#<URI::InvalidURIError: bad URI(is not URI?): "https://aaaa:aaaa:aaaa::1:443/api">`

**Expected**
Creates a client without any error

**Comment by cben** [comment]
I think when you want to specify a port number with IPv6 you must surround the IP with square brackets:
`https://[aaaa:aaaa:aaaa::1]:443/api`
Does that work?

**Comment by harshit-splunk** [comment]
Thanks! it worked.
