### ISSUE TITLE
Confusion around `kubeclient` latest version (`4.10.1` vs `4.10.0`)

### ISSUE THREAD

**Issue by cjoudrey** [ManageIQ/kubeclient#580]
👋 Hey @cben,

I was hoping you could shed some light on the latest version of `kubeclient`.

In `master`, `Kubeclient::VERSION` is `4.10.0` and the `CHANGELOG` seems to list it as being the latest version.

However, Rubygems suggests there exists a newer version (`4.10.1`) and a git tag exists for it as well.

Is `4.10.1` safe to use? Is it simply that the version bump did not make it to `master`?

Thanks! 😄

**Comment by agrare** [comment]
Hey @cjoudrey!  The master branch is tracking what will be 5.0, so 4.10* changes are merged to the `4.y` branch directly (see https://github.com/ManageIQ/kubeclient/pull/579) and then forward-ported to master (as done in https://github.com/ManageIQ/kubeclient/pull/575).  It looks like we simply forgot to forward-port the changes for v4.10.1 to master, this was an oversight but v4.10.1 is absolutely safe to use.

**Comment by cjoudrey** [comment]
Ahh, gotcha! Thanks for the quick reply and for the PR. 😄
